source 'https://rubygems.org'

gem 'bundler'
gem 'rake'

gem 'sneakers'
gem 'influxdb'
gem 'redis'

gem 'lotusrb'
gem 'lotus-model'
gem 'lotus-assets', github: 'lotus/assets'

gem 'foreman'

gem 'puma'

group :development do
  gem 'capistrano'
  gem 'capistrano-passenger'
  gem 'capistrano-rbenv'
end

group :test do
  gem 'rspec'
  gem 'capybara'
end
