humidity: sneakers work HumidityProcessor --require consumer.rb
movement: sneakers work MovementProcessor --require consumer.rb
temperature: sneakers work TemperatureProcessor --require consumer.rb
statistics: sneakers work StatisticsProcessor --require consumer.rb
